language: cpp
dist: trusty
script:
- make linux32
- make linux64
- make test
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      install:
      - sudo apt-get install -y -f g++-5-multilib g++-5-multilib:i386
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
env:
- CXX=g++-5