language: cpp
dist: trusty
compiler: g++
script:
- make linux32
- make linux64
- make test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
env:
- CXX=g++-5