language: cpp
compiler: g++
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
            - g++-5-multilib
            - lib32stdc++-5-dev
            - libx32stdc++-5-dev
            - cpp-5
            - gcc-5-multilib
            - libc6-dev-x32
            - lib32gcc-5-dev
            - libx32gcc-5-dev
            - libx32stdc++6
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      script:
      - make linux32
      - make linux64
      - make test
env:
- CXX=g++-5