language: cpp
dist: trusty
script:
- make linux32
- make linux64
- make test
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
            - g++-5-multilib
            - g++-5-multilib:i386
            - lib32stdc++-5-dev
            - libx32stdc++-5-dev
            - g++-5:i386
            - gcc-5-multilib:i386
            - cpp-5
            - gcc-5-multilib
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
env:
- CXX=g++-5