language: cpp
compiler: g++
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5
          - gcc-5
          - g++-5-multilib
          - lib32stdc++-5-dev
          - libx32stdc++-5-dev
          - cpp-5
          - gcc-5-multilib
          - libc6-dev-x32
          - lib32gcc-5-dev
          - libx32gcc-5-dev
          - libx32stdc++6
          - linux-libc-dev:i386
          - libcurl4-openssl-dev
      env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      script:
      - find /usr -name "libcurl*"
      - find /usr -name "libssl*"
      - find /usr -name "libcrypto*"
      - make linux32 CXX=g++-5
      - make linux64 CXX=g++-5
      - make test CXX=g++-5