version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: dependencies
          command: dpkg --add-architecture i386 && apt-get update && apt-get install -y -f build-essential software-properties-common g++-multilib gcc-multilib libc6-dev libc6-dev:i386 unzip zip wget
      - run:
          name: openssl
          command: make openssl
      - run:
          name: curl
          command: make curl
      - run:
          name: test x86 binary
          command: make test
      - run:
          name: x86 binary
          command: make linux32
      - store_artifacts:
          path: .build/@ArmA3URLFetch/arma3urlfetch.so
          destination: arma3urlfetch.so