version: 2
jobs:
  build_debian_x32:
    docker:
      - image: quay.io/playnet/arma3urlfetch-ci-debian:1
    steps:
      - run:
          command: apt-get install --fix-missing -f -y git
      - checkout
      - run:
          name: test x86 binary
          command: make test
      - run:
          name: build x86 binary
          command: make linux32
      - store_artifacts:
          path: .build/@ArmA3URLFetch/arma3urlfetch.so
          destination: arma3urlfetch.so
  build_debian_x64:
    docker:
      - image: quay.io/playnet/arma3urlfetch-ci-debian:x64
    steps:
      - run:
          command: apt-get install --fix-missing -f -y git
      - checkout
      - run:
          name: test x64 binary
          command: make testLinux64
      - run:
          name: build x64 binary
          command: make linux64
      - store_artifacts:
          path: .build/@ArmA3URLFetch/arma3urlfetch_x64.so
          destination: arma3urlfetch_x64.so
  linting:
    docker:
      - image: acemod/sqflint
    steps:
      - checkout
      - run:
          name: linting
          command: sqflint --exit=e -d addons
  build_mod:
    docker:
      - image: acemod/armake
    steps:
      - checkout
      - run:
          name: building
          command: make release
workflows:
  version: 2
  build:
    jobs:
      - linting
      - build_mod:
          requires:
            - linting
      - build_debian:
          requires:
            - linting
