version: 2
jobs:
  build_debian:
    docker:
      - image: quay.io/playnet/arma3urlfetch-ci-debian:1
    steps:
      - checkout
      - run:
          name: test x86 binary
          command: make test
      - run:
          name: x86 binary
          command: make linux32
      - store_artifacts:
          path: .build/@ArmA3URLFetch/arma3urlfetch.so
          destination: arma3urlfetch.so
  build_ubuntu:
    docker:
      - image: quay.io/playnet/arma3urlfetch-ci-ubuntu:1
    steps:
      - checkout
      - run:
          name: test x86 binary
          command: make test
      - run:
          name: x86 binary
          command: make linux32
      - store_artifacts:
          path: .build/@ArmA3URLFetch/arma3urlfetch.so
          destination: arma3urlfetch.so
  linting:
    docker:
      - image: quay.io/playnet/arma3urlfetch-ci-debian:1
    steps:
      - checkout
      - run:
          name: linting
          command: sqflint --exit=e -d addons
workflows:
  version: 2
  build:
    jobs:
      - linting
      - build_ubuntu:
          requires:
            - linting
      - build_debian:
          requires:
            - linting